-- Add sample postal codes for South African cities
-- This provides data for the address autocomplete functionality

INSERT INTO za_postal_codes (suburb, city, province, postal_code) VALUES
-- Cape Town
('Cape Town CBD', 'Cape Town', 'Western Cape', '8001'),
('Sea Point', 'Cape Town', 'Western Cape', '8005'),
('Green Point', 'Cape Town', 'Western Cape', '8005'),
('Gardens', 'Cape Town', 'Western Cape', '8001'),
('V&A Waterfront', 'Cape Town', 'Western Cape', '8001'),
('Camps Bay', 'Cape Town', 'Western Cape', '8005'),
('Clifton', 'Cape Town', 'Western Cape', '8005'),
('Bantry Bay', 'Cape Town', 'Western Cape', '8005'),
('Fresnaye', 'Cape Town', 'Western Cape', '8005'),
('Bakoven', 'Cape Town', 'Western Cape', '8005'),
('Llandudno', 'Cape Town', 'Western Cape', '7806'),
('Hout Bay', 'Cape Town', 'Western Cape', '7806'),
('Constantia', 'Cape Town', 'Western Cape', '7806'),
('Newlands', 'Cape Town', 'Western Cape', '7700'),
('Rondebosch', 'Cape Town', 'Western Cape', '7700'),
('Claremont', 'Cape Town', 'Western Cape', '7708'),
('Wynberg', 'Cape Town', 'Western Cape', '7800'),
('Observatory', 'Cape Town', 'Western Cape', '7925'),
('Mowbray', 'Cape Town', 'Western Cape', '7700'),
('Pinelands', 'Cape Town', 'Western Cape', '7405'),

-- Johannesburg
('Sandton', 'Johannesburg', 'Gauteng', '2196'),
('Rosebank', 'Johannesburg', 'Gauteng', '2196'),
('Melville', 'Johannesburg', 'Gauteng', '2109'),
('Parktown', 'Johannesburg', 'Gauteng', '2193'),
('Randburg', 'Johannesburg', 'Gauteng', '2194'),
('Midrand', 'Johannesburg', 'Gauteng', '1685'),
('Fourways', 'Johannesburg', 'Gauteng', '2055'),
('Bryanston', 'Johannesburg', 'Gauteng', '2191'),
('Morningside', 'Johannesburg', 'Gauteng', '2057'),
('Rivonia', 'Johannesburg', 'Gauteng', '2128'),
('Houghton', 'Johannesburg', 'Gauteng', '2041'),
('Saxonwold', 'Johannesburg', 'Gauteng', '2196'),
('Hyde Park', 'Johannesburg', 'Gauteng', '2196'),
('Sandhurst', 'Johannesburg', 'Gauteng', '2196'),
('Morningside', 'Johannesburg', 'Gauteng', '2057'),
('Bedfordview', 'Johannesburg', 'Gauteng', '2008'),
('Edenvale', 'Johannesburg', 'Gauteng', '1609'),
('Germiston', 'Johannesburg', 'Gauteng', '1401'),
('Benoni', 'Johannesburg', 'Gauteng', '1501'),
('Boksburg', 'Johannesburg', 'Gauteng', '1460'),

-- Pretoria
('Pretoria', 'Pretoria', 'Gauteng', '0002'),
('Centurion', 'Pretoria', 'Gauteng', '0157'),
('Hatfield', 'Pretoria', 'Gauteng', '0028'),
('Brooklyn', 'Pretoria', 'Gauteng', '0181'),
('Waterkloof', 'Pretoria', 'Gauteng', '0181'),
('Menlo Park', 'Pretoria', 'Gauteng', '0081'),
('Groenkloof', 'Pretoria', 'Gauteng', '0027'),
('Arcadia', 'Pretoria', 'Gauteng', '0007'),
('Sunnyside', 'Pretoria', 'Gauteng', '0002'),
('Muckleneuk', 'Pretoria', 'Gauteng', '0002'),

-- Durban
('Durban CBD', 'Durban', 'KwaZulu-Natal', '4001'),
('Umhlanga', 'Durban', 'KwaZulu-Natal', '4320'),
('Ballito', 'Durban', 'KwaZulu-Natal', '4420'),
('Pietermaritzburg', 'Pietermaritzburg', 'KwaZulu-Natal', '3201'),
('Westville', 'Durban', 'KwaZulu-Natal', '3629'),
('Pinetown', 'Durban', 'KwaZulu-Natal', '3610'),
('Hillcrest', 'Durban', 'KwaZulu-Natal', '3650'),
('Kloof', 'Durban', 'KwaZulu-Natal', '3640'),
('Gillitts', 'Durban', 'KwaZulu-Natal', '3625'),
('Botha\'s Hill', 'Durban', 'KwaZulu-Natal', '3660'),
('Morningside', 'Durban', 'KwaZulu-Natal', '4001'),
('Berea', 'Durban', 'KwaZulu-Natal', '4001'),
('Glenwood', 'Durban', 'KwaZulu-Natal', '4001'),
('Musgrave', 'Durban', 'KwaZulu-Natal', '4001'),
('Florida Road', 'Durban', 'KwaZulu-Natal', '4001'),

-- Other Major Cities
('Bloemfontein', 'Bloemfontein', 'Free State', '9301'),
('Port Elizabeth', 'Port Elizabeth', 'Eastern Cape', '6001'),
('East London', 'East London', 'Eastern Cape', '5200'),
('Polokwane', 'Polokwane', 'Limpopo', '0700'),
('Nelspruit', 'Nelspruit', 'Mpumalanga', '1200'),
('Kimberley', 'Kimberley', 'Northern Cape', '8301'),
('Rustenburg', 'Rustenburg', 'North West', '0300'),
('Potchefstroom', 'Potchefstroom', 'North West', '2520'),
('Welkom', 'Welkom', 'Free State', '9460'),
('Vereeniging', 'Vereeniging', 'Gauteng', '1930'),

-- Additional Cape Town suburbs
('Table View', 'Cape Town', 'Western Cape', '7441'),
('Milnerton', 'Cape Town', 'Western Cape', '7441'),
('Bloubergstrand', 'Cape Town', 'Western Cape', '7441'),
('Somerset West', 'Cape Town', 'Western Cape', '7130'),
('Stellenbosch', 'Stellenbosch', 'Western Cape', '7600'),
('Paarl', 'Paarl', 'Western Cape', '7620'),
('Franschhoek', 'Franschhoek', 'Western Cape', '7690'),
('Hermanus', 'Hermanus', 'Western Cape', '7200'),
('Knysna', 'Knysna', 'Western Cape', '6570'),
('George', 'George', 'Western Cape', '6530'),

-- Additional Johannesburg suburbs
('Roodepoort', 'Johannesburg', 'Gauteng', '1725'),
('Krugersdorp', 'Johannesburg', 'Gauteng', '1740'),
('Carletonville', 'Johannesburg', 'Gauteng', '2500'),
('Westonaria', 'Johannesburg', 'Gauteng', '1780'),
('Lenasia', 'Johannesburg', 'Gauteng', '1827'),
('Soweto', 'Johannesburg', 'Gauteng', '1804'),
('Diepsloot', 'Johannesburg', 'Gauteng', '2188'),
('Cosmo City', 'Johannesburg', 'Gauteng', '2188'),
('Northgate', 'Johannesburg', 'Gauteng', '2162'),
('Northriding', 'Johannesburg', 'Gauteng', '2162')

ON CONFLICT (suburb, city, province, postal_code) DO NOTHING;
